workflows:
  android-debug-apk:
    name: Build Debug APK
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android APK
        script: |
          brew install gradle
          mkdir -p ~/.android
          keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" || true
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" || true
          gradle signingReport
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
