package com.example.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage(val code: String, val displayName: String, val layoutDirection: LayoutDirection) {
    ENGLISH("en", "English", LayoutDirection.Ltr),
    ARABIC("ar", "العربية", LayoutDirection.Rtl)
}

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }

object Strings {
    @Composable
    fun get(key: String): String {
        val lang = LocalAppLanguage.current
        return get(key, lang)
    }

    fun get(key: String, language: AppLanguage): String {
        return if (language == AppLanguage.ARABIC) {
            arabicStrings[key] ?: englishStrings[key] ?: key
        } else {
            englishStrings[key] ?: key
        }
    }

    private val englishStrings = mapOf(
        "app_title" to "FamTasks",
        "app_tagline" to "Family Task Management & Rewards",
        "welcome" to "Welcome to FamTasks",
        "welcome_subtitle" to "Make family chores rewarding, organized, and fun!",
        "sign_in_with_google" to "Sign in with Google",
        "continue_with_google" to "Continue with Google",
        "sign_in" to "Sign In",
        "create_account" to "Create Account",
        "create_new_account_prefix" to "Don\'t have an account? Create a ",
        "new_account_link" to "new account",
        "already_have_account_prefix" to "Already have an account? ",
        "sign_in_link" to "Sign in",
        "first_name" to "First Name",
        "second_name" to "Second Name",
        "confirm_password" to "Confirm Password",
        "profile_setup_title" to "Complete Your Profile",
        "profile_setup_subtitle" to "Set up your name and optional profile picture to get started",
        "continue_button" to "Continue",
        "password_mismatch" to "Passwords do not match",
        "fill_all_fields" to "Please fill in all required fields",
        "invalid_email" to "Please enter a valid email address",
        "invalid_login_credentials" to "Invalid email or password",
        "or_divider" to "or",
        "sign_in_subtext" to "Connect securely to manage your family tasks and rewards",
        "manager_login" to "Super Admin / Manager Login",
        "manager_login_dialog_title" to "Super Admin Access",
        "manager_login_desc" to "Enter the designated credentials to access system management:",
        "email" to "Email",
        "password" to "Password",
        "login_button" to "Login as Super Admin",
        "cancel" to "Cancel",
        "invalid_credentials" to "Invalid Super Admin credentials",
        "create_family" to "Create New Family",
        "join_family" to "Join Existing Family",
        "family_name" to "Family Name",
        "join_code" to "Family Join Code",
        "join_code_hint" to "e.g. 6-digit code provided by your family admin",
        "submit_join_request" to "Request to Join",
        "request_pending" to "Join Request Pending Approval",
        "request_pending_desc" to "Your request has been submitted. Please wait for your Family Admin to approve.",
        "tasks" to "Tasks",
        "leaderboard" to "Leaderboard",
        "store" to "Store",
        "approvals" to "Approvals",
        "notifications" to "Notifications",
        "settings" to "Settings",
        "my_tasks" to "My Tasks",
        "all_tasks" to "All Family Tasks",
        "suggested_tasks" to "Suggestions",
        "add_task" to "Add Task",
        "suggest_task" to "Suggest Task",
        "task_name" to "Task Name",
        "task_description" to "Description",
        "points" to "Points",
        "assign_to" to "Assign To",
        "assign_to_me" to "Assign to Me (Admin)",
        "schedule_type" to "Schedule Type",
        "one_time" to "One-Time",
        "scheduled" to "Scheduled Date",
        "daily" to "Daily",
        "weekly" to "Weekly",
        "custom" to "Custom",
        "schedule_details" to "Schedule Details / Days",
        "recurring" to "Repeating Task",
        "mark_completed" to "Mark Completed",
        "completed" to "Completed",
        "pending_approval" to "Pending Approval",
        "pending_review" to "Pending Admin Review",
        "active" to "Active",
        "approve" to "Approve",
        "reject" to "Reject",
        "points_balance" to "Points Balance",
        "earned" to "Earned",
        "spent" to "Spent",
        "first_place" to "1st Place - Gold Champion",
        "second_place" to "2nd Place - Silver Star",
        "third_place" to "3rd Place - Bronze Star",
        "rank" to "Rank",
        "store_title" to "Family Rewards Store",
        "add_reward" to "Add Store Item",
        "item_name" to "Item Name",
        "item_price" to "Point Price",
        "target_audience" to "Available For",
        "whole_family" to "Whole Family",
        "specific_person" to "One Specific Person",
        "request_purchase" to "Request Purchase",
        "purchase_pending" to "Pending Approval",
        "purchased" to "Approved & Claimed",
        "rejected_purchase" to "Declined",
        "admin_note" to "Admin Note",
        "not_enough_points" to "Not enough points!",
        "pending_join_requests" to "Family Join Requests",
        "pending_task_suggestions" to "Task Suggestions",
        "pending_task_completions" to "Task Completion Reviews",
        "pending_purchases" to "Store Purchase Requests",
        "no_pending_approvals" to "No approvals pending right now! 🎉",
        "super_admin_dashboard" to "Super Admin / Manager Dashboard",
        "all_families" to "All Families",
        "manage_family" to "Manage Family",
        "change_admin" to "Change Family Admin",
        "delete_family" to "Delete Family",
        "all_users" to "All Users",
        "edit_points" to "Edit Points",
        "save" to "Save",
        "delete" to "Delete",
        "language_setting" to "App Language",
        "english" to "English",
        "arabic" to "العربية (Arabic)",
        "theme_setting" to "Theme & Appearance",
        "system_theme" to "System Default",
        "light_theme" to "Light Mode",
        "dark_theme" to "Dark Mode",
        "notification_settings" to "Notification Preferences",
        "notify_new_tasks" to "New Task Notifications",
        "notify_task_changes" to "Task Updates & Status Changes",
        "notify_store_items" to "New Store Item Alerts",
        "notify_purchases" to "Purchase Approval Alerts",
        "notify_approvals" to "Admin Approval Alerts",
        "sign_out" to "Sign Out",
        "role_super_admin" to "Super Admin / Manager",
        "role_family_admin" to "Family Admin",
        "role_family_member" to "Family Member",
        "copy_code" to "Copy Code",
        "code_copied" to "Join code copied to clipboard",
        "no_tasks_found" to "No tasks found here",
        "no_items_found" to "No store items available yet",
        "no_notifications" to "No notifications yet",
        "members_count" to "Members",
        "quantity" to "Quantity",
        "items_left" to "items left",
        "item_left" to "item left",
        "out_of_stock" to "Out of stock",
        "select_quantity" to "Select Quantity",
        "total_points" to "Total Points",
        "available_points" to "Available Points",
        "item_details" to "Item Details",
        "cancel_request" to "Cancel Request",
        "request_cancelled" to "Purchase request cancelled",
        "my_orders" to "My Requests",
        "images" to "Images",
        "add_image" to "Add Image",
        "remove_image" to "Remove Image",
        "primary_image" to "Primary",
        "points_reserved_note" to "Points are reserved immediately upon request",
        "edit_profile" to "Edit Profile",
        "profile_updated" to "Profile updated successfully!",
        "profile_picture" to "Profile Picture (Optional)",
        "choose_template" to "Choose Template",
        "upload_photo" to "Upload Photo",
        "remove_photo" to "Remove Photo",
        "save_changes" to "Save Changes"
    )

    private val arabicStrings = mapOf(
        "app_title" to "مهام العائلة",
        "app_tagline" to "إدارة المهام والمكافآت العائلية",
        "welcome" to "مرحباً بك في تطبيق مهام العائلة",
        "welcome_subtitle" to "اجعل الأعمال العائلية ممتعة ومنظمة ومجزية!",
        "sign_in_with_google" to "تسجيل الدخول عبر Google",
        "continue_with_google" to "المتابعة باستخدام Google",
        "sign_in" to "تسجيل الدخول",
        "create_account" to "إنشاء الحساب",
        "create_new_account_prefix" to "ليس لديك حساب؟ إنشاء ",
        "new_account_link" to "حساب جديد",
        "already_have_account_prefix" to "لديك حساب بالفعل؟ ",
        "sign_in_link" to "تسجيل الدخول",
        "first_name" to "الاسم الأول",
        "second_name" to "الاسم الثاني",
        "confirm_password" to "تأكيد كلمة المرور",
        "profile_setup_title" to "إكمال الملف الشخصي",
        "profile_setup_subtitle" to "أدخل اسمك واختر صورة الملف الشخصي للبدء",
        "continue_button" to "المتابعة",
        "password_mismatch" to "كلمات المرور غير متطابقة",
        "fill_all_fields" to "يرجى ملء جميع الحقول المطلوبة",
        "invalid_email" to "يرجى إدخال بريد إلكتروني صالح",
        "invalid_login_credentials" to "البريد الإلكتروني أو كلمة المرور غير صحيحة",
        "or_divider" to "أو",
        "sign_in_subtext" to "تسجيل آمن لإدارة مهام ومكافآت عائلتك",
        "manager_login" to "تسجيل دخول المدير العام (Super Admin)",
        "manager_login_dialog_title" to "دخول المدير العام",
        "manager_login_desc" to "أدخل البيانات المعتمدة للوصول إلى لوحة الإدارة العامة:",
        "email" to "البريد الإلكتروني",
        "password" to "كلمة المرور",
        "login_button" to "دخول كمدير عام",
        "cancel" to "إلغاء",
        "invalid_credentials" to "بيانات اعتماد المدير العام غير صحيحة",
        "create_family" to "إنشاء عائلة جديدة",
        "join_family" to "الانضمام إلى عائلة",
        "family_name" to "اسم العائلة",
        "join_code" to "رمز الانضمام للعائلة",
        "join_code_hint" to "مثال: الرمز المكون من 6 خانات من مسؤول العائلة",
        "submit_join_request" to "طلب الانضمام",
        "request_pending" to "طلب الانضمام قيد المراجعة",
        "request_pending_desc" to "تم إرسال طلبك. يرجى انتظار موافقة مسؤول العائلة.",
        "tasks" to "المهام",
        "leaderboard" to "المتصدرين",
        "store" to "المتجر",
        "approvals" to "الموافقات",
        "notifications" to "الإشعارات",
        "settings" to "الإعدادات",
        "my_tasks" to "مهامي",
        "all_tasks" to "كل مهام العائلة",
        "suggested_tasks" to "المقترحات",
        "add_task" to "إضافة مهمة",
        "suggest_task" to "اقتراح مهمة",
        "task_name" to "اسم المهمة",
        "task_description" to "الوصف والتفاصيل",
        "points" to "النقاط",
        "assign_to" to "تعيين إلى",
        "assign_to_me" to "تعيين لنفسي (المسؤول)",
        "schedule_type" to "نوع الجدول",
        "one_time" to "لمرة واحدة",
        "scheduled" to "تاريخ محدد",
        "daily" to "يومي",
        "weekly" to "أسبوعي",
        "custom" to "مخصص",
        "schedule_details" to "تفاصيل الجدول / الأيام",
        "recurring" to "مهمة متكررة",
        "mark_completed" to "إتمام المهمة",
        "completed" to "مكتملة",
        "pending_approval" to "بانتظار الموافقة",
        "pending_review" to "بانتظار مراجعة الإدارة",
        "active" to "نشطة",
        "approve" to "موافقة",
        "reject" to "رفض",
        "points_balance" to "رصيد النقاط",
        "earned" to "المكتسبة",
        "spent" to "المصروفة",
        "first_place" to "المركز الأول - البطل الذهبي 🥇",
        "second_place" to "المركز الثاني - النجم الفضي 🥈",
        "third_place" to "المركز الثالث - النجم البرونزي 🥉",
        "rank" to "الترتيب",
        "store_title" to "متجر مكافآت العائلة",
        "add_reward" to "إضافة مكافأة بالمتجر",
        "item_name" to "اسم العنصر / المكافأة",
        "item_price" to "السعر بالنقاط",
        "target_audience" to "متاح لمن",
        "whole_family" to "لكل أفراد العائلة",
        "specific_person" to "لشخص محدد فقط",
        "request_purchase" to "طلب الشراء",
        "purchase_pending" to "قيد المراجعة",
        "purchased" to "تم الشراء والموافقة",
        "rejected_purchase" to "تم الرفض",
        "admin_note" to "ملاحظة الإدارة",
        "not_enough_points" to "رصيد النقاط غير كافٍ!",
        "pending_join_requests" to "طلبات الانضمام للعائلة",
        "pending_task_suggestions" to "اقتراحات المهام",
        "pending_task_completions" to "مراجعة إتمام المهام",
        "pending_purchases" to "طلبات الشراء من المتجر",
        "no_pending_approvals" to "لا توجد موافقات معلقة حالياً! 🎉",
        "super_admin_dashboard" to "لوحة تحكم المدير العام (Super Admin)",
        "all_families" to "جميع العائلات",
        "manage_family" to "إدارة العائلة",
        "change_admin" to "تغيير مسؤول العائلة",
        "delete_family" to "حذف العائلة",
        "all_users" to "جميع المستخدمين",
        "edit_points" to "تعديل النقاط",
        "save" to "حفظ",
        "delete" to "حذف",
        "language_setting" to "لغة التطبيق",
        "english" to "English (الإنجليزية)",
        "arabic" to "العربية",
        "theme_setting" to "المظهر والسمة",
        "system_theme" to "تلقائي حسب النظام",
        "light_theme" to "الوضع الفاتح",
        "dark_theme" to "الوضع الداكن",
        "notification_settings" to "تفضيلات الإشعارات",
        "notify_new_tasks" to "إشعارات المهام الجديدة",
        "notify_task_changes" to "إشعارات تحديثات وحالة المهام",
        "notify_store_items" to "تنبيهات عناصر المتجر الجديدة",
        "notify_purchases" to "تنبيهات طلبات وموافقات الشراء",
        "notify_approvals" to "تنبيهات موافقات الإدارة",
        "sign_out" to "تسجيل الخروج",
        "role_super_admin" to "المدير العام (Super Admin)",
        "role_family_admin" to "مسؤول العائلة",
        "role_family_member" to "فرد في العائلة",
        "copy_code" to "نسخ الرمز",
        "code_copied" to "تم نسخ رمز الانضمام إلى الحافظة",
        "no_tasks_found" to "لا توجد مهام هنا",
        "no_items_found" to "لا توجد عناصر بالمتجر حالياً",
        "no_notifications" to "لا توجد إشعارات بعد",
        "members_count" to "أعضاء",
        "quantity" to "الكمية",
        "items_left" to "عناصر متبقية",
        "item_left" to "عنصر متبقي",
        "out_of_stock" to "نفدت الكمية",
        "select_quantity" to "تحديد الكمية",
        "total_points" to "إجمالي النقاط",
        "available_points" to "النقاط المتاحة",
        "item_details" to "تفاصيل العنصر",
        "cancel_request" to "إلغاء الطلب",
        "request_cancelled" to "تم إلغاء طلب الشراء",
        "my_orders" to "طلباتي",
        "images" to "الصور",
        "add_image" to "إضافة صورة",
        "remove_image" to "حذف الصورة",
        "primary_image" to "الرئيسية",
        "points_reserved_note" to "يتم حجز النقاط فور إرسال الطلب",
        "edit_profile" to "تعديل الملف الشخصي",
        "profile_updated" to "تم تحديث الملف الشخصي بنجاح!",
        "profile_picture" to "صورة الملف الشخصي (اختياري)",
        "choose_template" to "اختيار قالب",
        "upload_photo" to "رفع صورة",
        "remove_photo" to "حذف الصورة",
        "save_changes" to "حفظ التغييرات"
    )
}
